services:
  isx_installer:
    build: .
    volumes:
      - isx_python_api:/tmp/inscopix
      - ./isx_installer.sh:/opt/installer.sh:ro # rename locally Inscopix Data Processing 1.9.6.sh
      - ./output:/output
      - ./:/app:rw                                  # your repo root (optional)
      - ./ci_pipeline:/work/ci_pipeline:rw
    environment:
      - LOCAL_EDITABLE_DIR=/work/ci_pipeline
      - ISX_INSTALLER_PATH=/opt/installer.sh
      - EXPECTED_OUTPUT_FILE=/output/done.marker
    working_dir: /app
    stdin_open: true
    tty: true
    restart: "no"

volumes:
  isx_python_api:
